### ISSUE TITLE
Distorted camera ratio on some Androids

### ISSUE THREAD

**Issue by zepod** [rossumai/elis-capture#1]
@pasky reported that on his phone (Xiaomi redmi 6), camera is not selecting appropriate ratio, resulting in distorted display of camera. After photo is taken, image is of good ratio. It only looks bad when taking the photo.

**Comment by qiq** [comment]
Checked Moto X-Force (Android 7.0) and Nokia 6.1 (Android 9) and it works fine.

**Comment by qiq** [comment]
Because resulting image is OK, I consider this a non-blocking issue.

**Comment by zepod** [comment]
fixed in #15 by @EskelCz 👍
