### ISSUE TITLE
Splash screen blurry [android]

### ISSUE THREAD

**Issue by EskelCz** [rossumai/elis-capture#11]
Looking like a lower resolution version, upscaled

**Comment by zepod** [comment]
in `src/images` we have wide range of resolutions of icons. So there's no problem in picking a different one for splash screen...

However, I don't think the splash screen should have the icon as big as it is.. I'd make it smaller (around 30% of screen width wide)

**Comment by EskelCz** [comment]
Seems like a bug in Expo. Anyway it's just the default splash screen for Expo, it won't be seen by actual users
