### ISSUE TITLE
Captured images are too large for Elis

### ISSUE THREAD

**Issue by zepod** [rossumai/elis-capture#2]
When taking a photo, it's resolution needs to be downgraded and/or file compressed before it's sent to Elis API. With current setting, 15MB limit for documents is often exceeded

**Comment by qiq** [comment]
It turns out that we inflate image on the backend: when upload?join=true is used (no proper compression is used). Images could be scaled-down to cca 1200x1700 anyway.

**Comment by zepod** [comment]
Fixed in https://github.com/rossumai/elis-capture/pull/7
