### ISSUE TITLE
Resolve security issue of `merge` package

### ISSUE THREAD

**Issue by zepod** [rossumai/elis-capture#3]
https://github.com/rossumai/elis-capture/network/alert/yarn.lock/merge/open

**Comment by EskelCz** [comment]
The link is broken. What is this issue about?

**Comment by qiq** [comment]
The alert was shown by github, but it is not present any more... probably solved by new version of some package? @zepod should we close this?

**Comment by zepod** [comment]
Yea.. somehow solved. Don't care how.. closing
